# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('duration', models.DurationField(blank=True)),
                ('participants', models.IntegerField(default=1)),
                ('requirements', models.TextField(default='[]')),
                ('included', models.TextField(default='[]')),
                ('additional', models.TextField(blank=True)),
            ],
        ),
    ]
