# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='additional',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='included',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='requirements',
            field=models.TextField(),
        ),
    ]
