# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_demographic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='demographic',
            name='experiences',
        ),
        migrations.AddField(
            model_name='experience',
            name='categories',
            field=models.ManyToManyField(to='app.Category'),
        ),
        migrations.AddField(
            model_name='experience',
            name='demographics',
            field=models.ManyToManyField(to='app.Demographic'),
        ),
    ]
