# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20151219_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='additional',
            field=models.TextField(blank=True, help_text='Each one in a new line'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.DurationField(blank=True, help_text='Number of hours'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='included',
            field=models.TextField(blank=True, help_text='Each one in a new line'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='requirements',
            field=models.TextField(blank=True, help_text='Each one in a new line'),
        ),
    ]
