# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20151221_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='availability',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, help_text='Each one in a new line'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(max_length=250),
        ),
    ]
