# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20151221_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, help_text='Each paragraph in a new line'),
        ),
    ]
