# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20151221_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='demographics',
        ),
        migrations.AddField(
            model_name='experience',
            name='benefits',
            field=models.TextField(blank=True, help_text='Each one in a new line'),
        ),
        migrations.AddField(
            model_name='experience',
            name='gear',
            field=models.TextField(blank=True, help_text='Each one in a new line'),
        ),
        migrations.DeleteModel(
            name='Demographic',
        ),
    ]
