# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 23:11
from __future__ import unicode_literals
from django.db import migrations
from datetime import timedelta
from django.core.exceptions import ObjectDoesNotExist
from .. utils import text_as_json


EXPERIENCES_FILE_NEW = "app/migrations/0009_data/experiences_es_new.tsv"
EXPERIENCES_FILE_OLD = "app/migrations/0009_data/experiences_es_old.tsv"
NEW_LINE_DELIMITER = "|"

def insert_experiences(apps, schema_editor):
  experience_lines = read_lines_from_file(EXPERIENCES_FILE_NEW)[1:]

  Experience = apps.get_model("app", "Experience")
  Category = apps.get_model("app", "Category")

  for line in experience_lines:
    fields = line.decode('utf8').rstrip().split("\t")

    try:
      category = Category.objects.get(name=fields[10])
    except ObjectDoesNotExist:
      category = Category(name=fields[10])
      category.save()
    
    experience = Experience(
        name=fields[0],
        price=float(fields[1]),
        description=text_as_json(fields[2], NEW_LINE_DELIMITER),
        location=fields[3],
        availability=text_as_json(fields[4], NEW_LINE_DELIMITER),
        duration=timedelta(hours=float(fields[5])),
        participants=int(fields[6]),
        requirements=text_as_json(fields[7], NEW_LINE_DELIMITER),
        included=text_as_json(fields[8], NEW_LINE_DELIMITER),
        additional=text_as_json(fields[9], NEW_LINE_DELIMITER),
        benefits=text_as_json(fields[11], NEW_LINE_DELIMITER),
        gear=text_as_json(fields[12], NEW_LINE_DELIMITER)
    )
    experience.save()
    experience.categories.add(category)

def delete_experiences(apps, schema_editor):
  experience_lines = read_lines_from_file(EXPERIENCES_FILE_OLD)[1:]

  Experience = apps.get_model("app", "Experience")
  Category = apps.get_model("app", "Category")

  for line in experience_lines:
    fields = line.decode('utf8').split("\t")

    experience = Experience.objects.get(name=fields[0])
    category = Category.objects.get(name=fields[10])
    experience.categories.remove(category)
    experience.delete()

def read_lines_from_file(file_name):
  with open(file_name) as f:
    return f.readlines()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160126_2309'),
    ]

    operations = [
        migrations.RunPython(insert_experiences, delete_experiences),
    ]
