# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160217_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='availability',
            field=models.TextField(blank=True, help_text='Each day in a new line'),
        ),
    ]
