# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160217_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='participants',
        ),
        migrations.AddField(
            model_name='experience',
            name='itinerary',
            field=models.TextField(blank=True, help_text='Each paragraph in a new line'),
        ),
    ]
