# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160301_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='images',
        ),
        migrations.AddField(
            model_name='experience',
            name='images_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, default='app/static/app/images/experiences/default', path='app/static/app/images/experiences/'),
        ),
    ]
