# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 21:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_experience_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Number of hours'),
        ),
    ]
