# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20160329_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='people',
            field=models.IntegerField(default=1),
        ),
    ]
