# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20160415_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='subheader',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
