# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20160418_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='subheader',
        ),
        migrations.AddField(
            model_name='experience',
            name='experiences',
            field=models.ManyToManyField(related_name='_experience_experiences_+', to='app.Experience'),
        ),
    ]
