# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20160419_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='_experience_experiences_+', to='app.Experience'),
        ),
    ]
