# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20160512_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='images_path',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
